const router = require('express').Router()
const ctrl   = require('../controllers/personaje.controller')
const mejoras = require('../controllers/personaje_improvement.controller')
const pkFeatCtrl = require('../controllers/personaje_pokemon_feat.controller')
const improveCtrl = require('../controllers/personaje_pokemon_improvement.controller')
const descanso = require('../controllers/descanso.controller')
const { authenticate } = require('../middleware/auth.middleware')

router.get('/',                    authenticate, ctrl.getMine)
router.get('/party',               authenticate, ctrl.getParty)
router.get('/:id/full',            authenticate, ctrl.getFull)
router.get('/:id/equipo',          authenticate, ctrl.getEquipo)
router.post('/:id/equipo',         authenticate, ctrl.addEquipo)
router.patch('/:id/equipo/:idEquipo', authenticate, ctrl.updateEquipo)
router.get('/:id/armor',           authenticate, ctrl.getArmor)
router.post('/:id/armor',          authenticate, ctrl.addArmor)
router.patch('/:id/armor/:idArmor', authenticate, ctrl.updateArmorInUse)
router.patch('/:id/combate',       authenticate, ctrl.updateCombate)
router.patch('/:id/editable',      authenticate, ctrl.setEditable)
router.patch('/:id/pokedollars/add', authenticate, ctrl.addPokedollars)
router.patch('/:id/pokedollars',   authenticate, ctrl.spendPokedollars)
router.get('/:id/feats',           authenticate, ctrl.getFeats)
router.post('/:id/feats',          authenticate, ctrl.addFeat)
router.delete('/:id/feats/:idpf',  authenticate, ctrl.removeFeat)
router.patch('/:id/feats/:idpf/available', authenticate, ctrl.setFeatAvailable)
router.post('/:id/specializations',            authenticate, ctrl.addSpecialization)
router.delete('/:id/specializations/:idspec',  authenticate, ctrl.removeSpecialization)
router.get('/:id/pending-improvements', authenticate, improveCtrl.listPending)
router.post('/:id/pokemon/:idpp/improvement/moves', authenticate, improveCtrl.confirmMoves)
router.post('/:id/pokemon/:idpp/improvement/asi',   authenticate, improveCtrl.confirmAsi)
router.get('/:id/pokemon/pending-rename', authenticate, ctrl.pendingRenames)
router.get('/:id/pokemon',         authenticate, ctrl.getPokemon)
router.post('/:id/pokemon',        authenticate, ctrl.addPokemon)

router.put('/:id/pokemon/:idpp/bond', authenticate, ctrl.updateBondPoints)

// Recursos que otorga la ruta (puntos gastables, tipo PP)
router.patch('/:id/path-resource/:idb', authenticate, ctrl.spendPathResource)
router.put('/:id/path-resource/:idb',   authenticate, ctrl.setPathResource)

// Dados de golpe gastables (hit_dice_left sobre hit_dice_pool), tipo PP
router.patch('/:id/hit-dice',                authenticate, ctrl.spendHitDice)
router.put('/:id/hit-dice',                  authenticate, ctrl.setHitDice)
router.patch('/:id/pokemon/:idpp/hit-dice',  authenticate, ctrl.spendHitDicePokemon)
router.put('/:id/pokemon/:idpp/hit-dice',    authenticate, ctrl.setHitDicePokemon)

// Descansos: quiénes pueden tomarlo y su aplicación
router.get('/:id/rest',        authenticate, descanso.getParticipantes)
router.post('/:id/rest/long',  authenticate, descanso.longRest)
router.post('/:id/rest/short', authenticate, descanso.shortRest)

// Mejoras de nivel del entrenador
router.get('/:id/improvements',                        authenticate, mejoras.getPending)
router.get('/:id/improvements/specializations',        authenticate, mejoras.getSpecs)
router.post('/:id/improvements/:pendingId/confirm',    authenticate, mejoras.confirm)
router.patch('/:id/pokemon/:idpp/combate', authenticate, ctrl.updatePokemonCombate)
router.get('/:id/pokemon/:idpp',   authenticate, ctrl.getPokemonDetail)
router.patch('/:id/pokemon/:idpp/en-equipo', authenticate, ctrl.updatePokemonEnEquipo)
router.patch('/:id/pokemon/:idpp/en-juego',  authenticate, ctrl.updatePokemonEnJuego)
router.patch('/:id/pokemon/:idpp/experiencia', authenticate, ctrl.addPokemonExperience)
router.patch('/:id/pokemon/:idpp/apodo',       authenticate, ctrl.renamePokemon)
router.patch('/:id/pokemon/:idpp/moves/:idrow/pp', authenticate, ctrl.spendMovePP)
router.put('/:id/pokemon/:idpp/moves/:idrow/pp',   authenticate, ctrl.setMovePP)
router.post('/:id/pokemon/:idpp/transfer',     authenticate, ctrl.transferPokemon)
router.delete('/:id/pokemon/:idpp',            authenticate, ctrl.releasePokemon)
router.get('/:id/pokemon/:idpp/feats',                     authenticate, pkFeatCtrl.getFeats)
router.post('/:id/pokemon/:idpp/feats',                    authenticate, pkFeatCtrl.addFeat)
router.delete('/:id/pokemon/:idpp/feats/:idfeat',          authenticate, pkFeatCtrl.removeFeat)
router.patch('/:id/pokemon/:idpp/feats/:idfeat/available', authenticate, pkFeatCtrl.setFeatAvailable)
router.get('/:id/weapon',          authenticate, ctrl.getWeapon)
router.post('/:id/weapon',         authenticate, ctrl.addWeapon)
router.patch('/:id/weapon/:idWeapon', authenticate, ctrl.updateWeaponInUse)
router.get('/:id',                 authenticate, ctrl.getById)
router.post('/',                   authenticate, ctrl.create)

module.exports = router
