const router = require('express').Router()
const ctrl   = require('../controllers/personaje.controller')
const { authenticate } = require('../middleware/auth.middleware')

router.get('/',                    authenticate, ctrl.getMine)
router.get('/party',               authenticate, ctrl.getParty)
router.get('/:id/full',            authenticate, ctrl.getFull)
router.get('/:id/equipo',          authenticate, ctrl.getEquipo)
router.post('/:id/equipo',         authenticate, ctrl.addEquipo)
router.patch('/:id/equipo/:idEquipo', authenticate, ctrl.updateEquipo)
router.get('/:id/armor',           authenticate, ctrl.getArmor)
router.post('/:id/armor',          authenticate, ctrl.addArmor)
router.patch('/:id/armor/:idArmor', authenticate, ctrl.updateArmorInUse)
router.patch('/:id/combate',       authenticate, ctrl.updateCombate)
router.patch('/:id/editable',      authenticate, ctrl.setEditable)
router.patch('/:id/pokedollars/add', authenticate, ctrl.addPokedollars)
router.patch('/:id/pokedollars',   authenticate, ctrl.spendPokedollars)
router.get('/:id/feats',           authenticate, ctrl.getFeats)
router.post('/:id/feats',          authenticate, ctrl.addFeat)
router.delete('/:id/feats/:idpf',  authenticate, ctrl.removeFeat)
router.patch('/:id/feats/:idpf/available', authenticate, ctrl.setFeatAvailable)
router.get('/:id/pokemon',         authenticate, ctrl.getPokemon)
router.post('/:id/pokemon',        authenticate, ctrl.addPokemon)
router.patch('/:id/pokemon/:idpp/combate', authenticate, ctrl.updatePokemonCombate)
router.get('/:id/pokemon/:idpp',   authenticate, ctrl.getPokemonDetail)
router.patch('/:id/pokemon/:idpp/en-equipo', authenticate, ctrl.updatePokemonEnEquipo)
router.get('/:id/weapon',          authenticate, ctrl.getWeapon)
router.post('/:id/weapon',         authenticate, ctrl.addWeapon)
router.patch('/:id/weapon/:idWeapon', authenticate, ctrl.updateWeaponInUse)
router.get('/:id',                 authenticate, ctrl.getById)
router.post('/',                   authenticate, ctrl.create)

module.exports = router
