-- El bulk-load inicial de las tablas de catálogo (pokemon, moves, items,
-- feats, y otras 22 más) insertó los ids a mano, sin pasar nunca por la
-- identity sequence de la columna. La sequence existe (todas estas columnas
-- son GENERATED BY DEFAULT AS IDENTITY) pero se quedó en 0/1, muy por detrás
-- del id real más alto de la tabla: items en 9 contra un máximo real de 463,
-- pokemon y moves ni siquiera se habían tocado nunca (is_called = false),
-- feats en 5 contra 90.
--
-- Por eso items.service.js calculaba MAX(item_id)+1 a mano en el propio
-- INSERT: confiar en la identity column tal como estaba habría repartido ids
-- ya ocupados. Ese cálculo manual funciona pero tiene una carrera real: dos
-- creaciones a la vez pueden calcular el mismo siguiente id antes de que
-- ninguna de las dos haya confirmado la suya.
--
-- Esta migración deja cada sequence en MAX(id)+1, para que un INSERT que no
-- especifique el id (dejando que la identity column lo genere) simplemente
-- funcione, sin carrera. Usa pg_get_serial_sequence() para resolver el
-- nombre real de cada sequence en vez de asumirlo: Postgres trunca a 63
-- caracteres los nombres de tabla+columna largos (por ejemplo,
-- trainer_pokemon_level_requirements queda como
-- trainer_pokemon_level_require_trainer_pokemon_level_require_seq), así que
-- adivinar el nombre a mano habría fallado justo en esos casos.
DO $$
DECLARE
  tabla_col text[][] := ARRAY[
    ARRAY['TM', 'tm_id'],
    ARRAY['abilities', 'ability_id'],
    ARRAY['armor_types', 'armor_type_id'],
    ARRAY['backgrounds', 'background_id'],
    ARRAY['bonds', 'bond_id'],
    ARRAY['evolution', 'evolution_id'],
    ARRAY['feats', 'feat_id'],
    ARRAY['items', 'item_id'],
    ARRAY['moves', 'move_id'],
    ARRAY['natures', 'nature_id'],
    ARRAY['origins', 'origin_id'],
    ARRAY['path_bonus', 'path_bonus_id'],
    ARRAY['paths', 'path_id'],
    ARRAY['personaje_path_bonus', 'personaje_path_bonus_id'],
    ARRAY['personaje_pending_improvement', 'personaje_pending_improvement_id'],
    ARRAY['personaje_pokemon_pasiva', 'id_personaje_pokemon_pasiva_id'],
    ARRAY['pokemon', 'pokemon_id'],
    ARRAY['pokemon_experience_levels', 'pokemon_experience_level_id'],
    ARRAY['pokemon_levels', 'pokemon_level_id'],
    ARRAY['pokemon_types', 'pokemon_types_id'],
    ARRAY['specializations', 'specialization_id'],
    ARRAY['trainer_levels', 'trainer_level_id'],
    ARRAY['trainer_pokemon_level_requirements', 'trainer_pokemon_level_requirement_id'],
    ARRAY['type_effectiveness', 'type_effectiveness_id'],
    ARRAY['weapon_properties', 'weapon_property_id'],
    ARRAY['weapon_types', 'weapon_type_id']
  ];
  fila text[];
  tabla text;
  columna text;
  secuencia text;
BEGIN
  FOREACH fila SLICE 1 IN ARRAY tabla_col LOOP
    tabla   := fila[1];
    columna := fila[2];
    secuencia := pg_get_serial_sequence(format('"{{schema}}".%I', tabla), columna);

    IF secuencia IS NULL THEN
      RAISE NOTICE 'Sin sequence: %.% (se salta)', tabla, columna;
      CONTINUE;
    END IF;

    EXECUTE format(
      'SELECT setval(%L, COALESCE((SELECT MAX(%I) FROM "{{schema}}".%I), 0) + 1, false)',
      secuencia, columna, tabla
    );
  END LOOP;
END $$;
