-- Quién está invocado en el campo (Pokémon/NPC del máster) vivía solo en
-- memoria del navegador, repartido por broadcast de Supabase: al recargar o
-- reconectar se perdía, y solo "sobrevivía" por casualidad si algún jugador
-- seguía conectado y se lo reenviaba al máster al volver.
--
-- Esta tabla guarda el hecho de "está invocado ahora, en esta partida" y sus
-- banderas por instancia (oculto, en la pokébola). El resto -HP, moves, feats-
-- ya se persiste o se recalcula aparte; no hace falta duplicarlo aquí.
--
-- Va por id_partida y no solo por id_master porque el mismo Pokémon/NPC del
-- catálogo del máster puede en teoría invocarse en partidas distintas, y el
-- campo es un estado de LA MESA, no del catálogo.
CREATE TABLE IF NOT EXISTS "{{schema}}"."master_campo" (
  id_campo          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_partida        integer NOT NULL REFERENCES "{{schema}}"."partida"(id_partida) ON DELETE CASCADE,
  id_master_pokemon integer REFERENCES "{{schema}}"."master_pokemon"(id_master_pokemon) ON DELETE CASCADE,
  id_master_npc     integer REFERENCES "{{schema}}"."master_npc"(id_master_npc) ON DELETE CASCADE,
  campo_hidden      boolean NOT NULL DEFAULT true,
  campo_in_ball     boolean NOT NULL DEFAULT false,
  created_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT master_campo_exactamente_uno CHECK (
    ((id_master_pokemon IS NOT NULL)::int + (id_master_npc IS NOT NULL)::int) = 1
  )
);

-- El mismo Pokémon/NPC del catálogo no puede estar invocado dos veces a la vez
-- en la misma partida (mismo criterio que ya aplicaba el picker en el cliente).
CREATE UNIQUE INDEX IF NOT EXISTS master_campo_pokemon_unico
  ON "{{schema}}"."master_campo" (id_partida, id_master_pokemon)
  WHERE id_master_pokemon IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS master_campo_npc_unico
  ON "{{schema}}"."master_campo" (id_partida, id_master_npc)
  WHERE id_master_npc IS NOT NULL;
