-- Registro de actividad de la mesa (quién usó qué item, quién atacó, quién
-- atrapó a quién...). Antes vivía solo en memoria de cada navegador, repartido
-- por broadcast de Supabase: al recargar o reconectar se perdía entero, y solo
-- "sobrevivía" por casualidad si algún otro jugador seguía conectado.
--
-- Los ataques de un Pokémon OCULTO del máster llevan dos versiones del texto:
-- la pública (que no delata la especie, "el pokemon usó Tackle") y la real
-- (partida_log_texto_master). Cuál se devuelve se decide al leer, según el rol
-- de quien consulta, no al guardar -así una vez que el máster lo revele, el
-- historial ya visto por los jugadores no cambia solo, pero el máster sigue
-- viendo el suyo propio con el nombre real-.
CREATE TABLE IF NOT EXISTS "{{schema}}"."partida_log" (
  id_partida_log           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_partida               integer NOT NULL REFERENCES "{{schema}}"."partida"(id_partida) ON DELETE CASCADE,
  partida_log_texto        text NOT NULL,
  partida_log_texto_master text,
  partida_log_role         text NOT NULL DEFAULT 'master',
  partida_log_created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS partida_log_por_partida
  ON "{{schema}}"."partida_log" (id_partida, id_partida_log);
